// Generated by tools/stub.mjs from contracts/greet.json — do not edit.
// Every symbol the contract declares exists here and throws: a parent may be
// built and loaded against this file, but nothing can pass a gate through it.

import process from 'node:process';

const rank = (v) => v.split('.').reduce((a, n, i) => a + Number(n) * 1000 ** (2 - i), 0);
if (rank(process.versions.node) < rank('20')) {
  throw new Error('stub greet: env pin "node>=20" is not satisfied by node ' + process.versions.node);
}

export const __stub = { contract: 'greet', env: 'node>=20', symbols: ['greet', 'shout'] };

export function greet() {
  throw new Error('not implemented: greet/greet');
}

export function shout() {
  throw new Error('not implemented: greet/shout');
}
