// Generated by tools/stub.mjs from contracts/greet.json — do not edit.
// The type-only view of the same stub: a parent type-checks against these
// declarations before the child contract has an implementation.

export declare const __stub: { contract: string; env: string; symbols: readonly string[] };

export declare function greet(name: string): string;
export declare function shout(name: string): string;
