#!/usr/bin/env node
// Materializes a contract's interface as a stub: a module whose every declared
// symbol exists and throws. A parent can be built, loaded and type-checked
// against it before the child contract has any implementation — the software
// analogue of proving against a sorry-stubbed statement. Spec: STUBS.md.
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const FORMATS = ['mjs', 'dts'];
const VALUE_FLAGS = ['--dir', '--format', '--out'];
const DECLARATION = /^export function ([A-Za-z_$][\w$]*)\((.*)\)\s*:\s*(.+);$/;
// Only a node pin can be enforced from node; any other toolchain's pin travels
// with the stub as metadata for that toolchain's own gate to enforce.
const NODE_PIN = /^node\s*>=\s*(\d+(?:\.\d+)*)$/;

const args = process.argv.slice(2);
const value = (flag, fallback) => {
  const i = args.indexOf(flag);
  return i === -1 ? fallback : args[i + 1];
};
const positional = args.filter((a, i) => !a.startsWith('--') && !VALUE_FLAGS.includes(args[i - 1]));
const dirArg = value('--dir', '.');
const dir = path.resolve(dirArg);
const format = value('--format', 'mjs');
const out = value('--out', null);
const check = args.includes('--check');
const name = positional[0];

const die = (...lines) => {
  for (const l of lines) console.error(l);
  process.exit(1);
};

if (!name) die('usage: node tools/stub.mjs <contract> [--dir p] [--format mjs|dts] [--out file] [--check]');
if (!FORMATS.includes(format)) die(`unknown --format "${format}" — use ${FORMATS.join(' or ')}`);
if (check && !out) die('--check needs --out: it compares a committed stub against a freshly generated one');

const source = `contracts/${name}.json`;
const file = path.join(dir, 'contracts', `${name}.json`);
if (!fs.existsSync(file)) die(`no contract "${name}": ${file} does not exist`);

let contract;
try {
  contract = JSON.parse(fs.readFileSync(file, 'utf8'));
} catch (e) {
  die(`${file}: invalid JSON (${e.message})`);
}

const block = /```stub\r?\n([\s\S]*?)```/.exec(contract.interface ?? '');
if (!block) {
  die(
    `contract "${name}": its interface has no \`\`\`stub block, so no stub can be generated from it.`,
    'Declare the exported symbols in a fenced stub block inside the interface — see STUBS.md.',
  );
}

const symbols = [];
block[1].split('\n').forEach((raw, i) => {
  const line = raw.trim();
  if (line === '' || line.startsWith('//')) return;
  const m = DECLARATION.exec(line);
  if (!m) {
    die(
      `contract "${name}", stub block line ${i + 1}: "${line}"`,
      'Each declaration must read "export function <name>(<params>): <type>;" — see STUBS.md.',
    );
  }
  if (symbols.some((s) => s.name === m[1])) die(`contract "${name}": stub block declares "${m[1]}" twice`);
  symbols.push({ name: m[1], params: m[2].trim(), returns: m[3].trim() });
});
if (symbols.length === 0) die(`contract "${name}": its stub block declares no symbols — see STUBS.md`);

const env = contract.env ?? '';
const pin = NODE_PIN.exec(env);
const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

const header = (note) => [
  `// Generated by tools/stub.mjs from ${source} — do not edit.`,
  ...note,
  '',
];

const renderMjs = () => {
  const lines = header([
    '// Every symbol the contract declares exists here and throws: a parent may be',
    '// built and loaded against this file, but nothing can pass a gate through it.',
  ]);
  if (pin) {
    lines.push("import process from 'node:process';", '');
    lines.push('const rank = (v) => v.split(\'.\').reduce((a, n, i) => a + Number(n) * 1000 ** (2 - i), 0);');
    lines.push(`if (rank(process.versions.node) < rank(${q(pin[1])})) {`);
    lines.push(`  throw new Error('stub ${name}: env pin "${env}" is not satisfied by node ' + process.versions.node);`);
    lines.push('}', '');
  }
  lines.push(
    `export const __stub = { contract: ${q(name)}, env: ${q(env)}, symbols: [${symbols.map((s) => q(s.name)).join(', ')}] };`,
    '',
  );
  // The runtime stub declares no parameters: arity and types are the compiler's
  // job, checked against the .d.mts the same contract generates.
  for (const s of symbols) {
    lines.push(`export function ${s.name}() {`, `  throw new Error('not implemented: ${name}/${s.name}');`, '}', '');
  }
  return lines.join('\n');
};

const renderDts = () => {
  const lines = header([
    '// The type-only view of the same stub: a parent type-checks against these',
    '// declarations before the child contract has an implementation.',
  ]);
  lines.push('export declare const __stub: { contract: string; env: string; symbols: readonly string[] };', '');
  for (const s of symbols) lines.push(`export declare function ${s.name}(${s.params}): ${s.returns};`);
  lines.push('');
  return lines.join('\n');
};

const text = format === 'mjs' ? renderMjs() : renderDts();

if (check) {
  if (fs.existsSync(out) && fs.readFileSync(out, 'utf8') === text) {
    console.log(`stub up to date: ${out}`);
    process.exit(0);
  }
  die(
    `stub out of date: ${out} is not what ${source} generates — regenerate with:`,
    `  node tools/stub.mjs ${name} --dir ${dirArg} --format ${format} --out ${out}`,
  );
}

if (out) {
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, text);
  console.log(`wrote ${out} — ${symbols.length} symbol(s) from contract "${name}"`);
} else {
  process.stdout.write(text);
}
